language: node_js
sudo: false
matrix:
  include:
  - node_js: 4
  - node_js: stable
  - node_js: 4
    env: KARMA=true
  fast_finish: true
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script: gulp test
after_success:
- cat coverage/*/lcov.info > coveralls.txt
- cat coveralls.txt | node_modules/coveralls/bin/coveralls.js
deploy:
  - skip_cleanup: true
    provider: script
    script: npm run branch-release
    on:
      branch: master
  - skip_cleanup: true
    provider: script
    script: npm run deploy
    on:
      branch: releases
      tags: true
