language: node_js
sudo: false
matrix:
  include:
  - node_js: 4
  - node_js: stable
  - node_js: 4
    env: KARMA=true
  fast_finish: true
env:
  global:
  - GIT_AUTHOR_EMAIL: APIs-GuruBot@users.noreply.github.com
  - GIT_AUTHOR_NAME: APIs-GuruBot
  - secure: RVRJijZYQ1MJnXi5iEUlmskCFnaYtM+DEAs8lffTpHVoHnArT6kQevQn0OY/BMjvTuviEvh6RFEB2SAIBUlTH7wHHhExk3q8h3w3AwPcU8AKvJFb4CcItz0MSYKNkua/fgbp2EzFC/kuB9JYdQP1MDfHSJc6JWhgYBuXSIj/H02/cBZDNPmtPIa0FNOlAD97LJraJ3yjtTJLO6c5u71VQPsO7P3KccTs4F5WzMC0kZwAPfXSLXju+o9TFj5wiLg1+6OwH0eZ4hDKSUS4+tkSTk0AqBXCYnUahlxBovIZBE/fKWqE8JQlL0tSuZxbrf0I01hoyFUVWdd3Uz4azT/VI0WQ9cUOotDOfHZ5NojYP9KSitlK/awmr3pqBVqacrq2n3h8BJo3CgVfKKzu1xUonBP3dkDLPgfjCztj0+IeJ3dTSpODADjrykVKujR0ZNk1e2l76UJc706gyAq/4EYPgPE0qhEVEyuTOMtGpK2FDL/InhD1XZSVlT93ZlBcfHwsBAtPLbWAygFHVOBygWTJJYKhf46CqddAxKi4aBmcDvxSihHY71vbB7OrJjHRxfEstOUJvTfQX8CDJmo0nIHu6gW9XL+9juauNW62bAkgTPyTBydxPTAKX4b4mVK9lnjER7V8ARx3UmVwDbw0v++fK+AOKul8FLlEhFED9wY4yaE=
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script: gulp test
after_success:
- cat coverage/*/lcov.info > coveralls.txt
- cat coveralls.txt | node_modules/coveralls/bin/coveralls.js
deploy:
- skip_cleanup: true
  provider: script
  script: npm run branch-release
  on:
    branch: master
- skip_cleanup: true
  provider: script
  script: npm run deploy
  on:
    branch: releases
    tags: true
